services:
  fiambreria-bot:
    build: .
    container_name: asistente
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Persistir la base de datos
      - ./db:/app/db
      # Si tienes credentials de Google Sheets
      - ./credentials.json:/app/credentials.json:ro
    environment:
      - TZ=America/Argentina/Buenos_Aires
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

