services:
  asistente:
    build: .
    container_name: asistente
    restart: unless-stopped
    volumes:
      - ./credential.json:/app/credential.json:ro
      - ./logs:/app/logs
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TZ=America/Argentina/Buenos_Aires
    env_file:
      - .env
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

